# Generated by Django 3.0.8 on 2020-09-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20200914_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
