# Generated by Django 3.0.8 on 2020-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20200914_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img_url',
            field=models.CharField(max_length=100, null=True, verbose_name='头像'),
        ),
    ]
