# Generated by Django 3.0.8 on 2020-09-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_comment_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_name',
            field=models.CharField(max_length=100, null=True, verbose_name='回复名称'),
        ),
    ]
